# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.Group'),
        ),
    ]
