# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160804_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date when this record was created.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date when this record was last updated.')),
                ('date', models.DateField()),
                ('attended', models.BooleanField(default=False)),
                ('absent_reason', models.CharField(choices=[('Unknown', 'Unknown'), ('Sick', 'Sick'), ('In Service', 'In Service'), ('Travel', 'Travel')], default='Unknown', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='GroupAttendancee',
            new_name='GroupAttendance',
        ),
        migrations.RemoveField(
            model_name='memberattendancee',
            name='event',
        ),
        migrations.RemoveField(
            model_name='memberattendancee',
            name='member',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('name', 'organization')]),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('name', 'organization')]),
        ),
        migrations.DeleteModel(
            name='MemberAttendancee',
        ),
        migrations.AddField(
            model_name='memberattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
        migrations.AddField(
            model_name='memberattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member'),
        ),
    ]
