# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160810_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date when this record was created.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date when this record was last updated.')),
                ('date', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='MemberAttendance',
            new_name='EventAttendance',
        ),
        migrations.RenameModel(
            old_name='MemberNotes',
            new_name='MemberNote',
        ),
        migrations.RemoveField(
            model_name='groupattendance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='groupattendance',
            name='group',
        ),
        migrations.RenameField(
            model_name='membernote',
            old_name='notes',
            new_name='note',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Weekly', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Active', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('name', 'group', 'organization')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together=set([('date', 'member', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='membergroup',
            unique_together=set([('member', 'group', 'member_type')]),
        ),
        migrations.DeleteModel(
            name='GroupAttendance',
        ),
        migrations.AddField(
            model_name='eventnote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventnote',
            unique_together=set([('date', 'event')]),
        ),
    ]
